spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    #  ??????
    publisher-confirms: true
    #  ??????
    publisher-returns: true
    listener:
      simple:
        #  ??????
        acknowledge-mode: manual
        #  ???????
        concurrency: 1
        #  ???
        max-concurrency: 1
        #  ??????
        retry:
          enabled: true


